name: Update YouTube Visualization

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update_visualization:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn requests

    - name: Run Analysis Script
      run: |
        python analysis_script.py

      working-directory: Youtube_10_popular_count

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add views_by_channel.png
        git commit -m "Update visualization with the latest data"
        git push origin main  # Push to main branch since your GitHub Pages deploys from here
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
